GET http://localhost:8080/rest/api/cityinfo
Accept: application/json
###
GET http://localhost:8080/rest/api/cityinfo/2300
Accept: application/json
###
GET http://localhost:8080/rest/api/cityinfo/cityByName/Valby
Accept: application/json
###